import 'react-native-get-random-values';
import React,{useCallback,useEffect,useState}from'react';
import{StyleSheet}from'react-native';
import{GestureHandlerRootView}from'react-native-gesture-handler';
import{Provider}from'react-redux';
import{PersistGate}from'redux-persist/integration/react';
import{NavigationContainer}from'@react-navigation/native';
import{StackScreens}from'scenes';
import{LanguageContext}from'context/language';
import{loadLanguage,setLanguage}from'i18n';
import{navigationRef}from'utils/navigation';
import Container from'components/Container';
import View from'components/View';
import Loading from'components/Loading';
import storage,{persistor}from'data/redux';
const App=():React.JSX.Element=>{const[isLoading,setIsLoading]=useState(true);const[currentLanguage,setCurrentLanguage]=useState('vi');const init=useCallback(async()=>{const l=await loadLanguage();setCurrentLanguage(l);setIsLoading(false)},[]);useEffect(()=>{init().catch(e=>console.error(JSON.stringify(e)))},[init]);const onChangeCurrentLanguage=useCallback((language:string)=>{setCurrentLanguage(language);setLanguage(language)},[]);return <GestureHandlerRootView style={styles.container}><Provider store={storage}><PersistGate loading={<Loading isLoading/>} persistor={persistor}><LanguageContext.Provider value={{language:currentLanguage,setLanguage:onChangeCurrentLanguage}}><NavigationContainer ref={navigationRef}>{isLoading?<Container isLoading><View/></Container>:<StackScreens/>}</NavigationContainer></LanguageContext.Provider></PersistGate></Provider></GestureHandlerRootView>};
const styles=StyleSheet.create({container:{flex:1}});export default App;
