import {StyleSheet} from 'react-native';
import colors from 'configuration/colors';
import {scale as responsiveScale} from 'utils/responsive';

const styles = StyleSheet.create({
  container: {
    borderRadius: 30,
    backgroundColor: '#140708',
  },
  button: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#4A1E20',
    borderRadius: 80,
    paddingBottom: responsiveScale(10),
    backgroundColor: '#1C0C0D',
  },
  leftContainer: {
    height: '100%',
    position: 'absolute',
    left: 0,
  },
  ballsWrapper: {
    flexWrap: 'wrap',
    maxWidth: '20%',
  },
  buttonEndTurn: {
    backgroundColor: '#B31217',
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    paddingHorizontal: responsiveScale(30),
    borderWidth: 1.2,
    borderColor: '#FF5858',
    shadowColor: '#FF3030',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    elevation: 8,
  },
  buttonEndTurnEmpty: {
    paddingHorizontal: responsiveScale(30),
  },
  totalPointWrapper: {
    marginBottom: responsiveScale(-56),
    marginHorizontal: responsiveScale(64),
  },
  totalPointNoMarginBottom: {
    marginBottom: 0,
    marginHorizontal: responsiveScale(64),
  },

  arenaContainer: {
    flex: 1,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: '#090A0E',
    borderWidth: 1.2,
    borderColor: '#7A1115',
    shadowColor: '#FF1E1E',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: {width: 0, height: 0},
    elevation: 7,
  },
  arenaContainerActive: {
    borderColor: '#FF2D2D',
    shadowOpacity: 0.34,
    shadowRadius: 20,
    elevation: 12,
  },
  arenaAdjustRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 6,
    marginBottom: 10,
  },
  arenaAdjustButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 20,
    backgroundColor: '#8B8B8B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaAdjustText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
    marginTop: -2,
  },
  arenaMetricsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  arenaMetricCard: {
    flex: 1,
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaMetricLabel: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
    opacity: 0.95,
  },
  arenaMetricValue: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
  },
  arenaScoreShell: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 2,
  },
  arenaScoreRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  arenaScoredBalls: {
    width: 34,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingTop: 18,
  },
  arenaScoreCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaScoreText: {
    color: '#FFFFFF',
    fontSize: 188,
    fontWeight: '400',
    lineHeight: 192,
    textShadowColor: 'rgba(255,255,255,0.08)',
    textShadowRadius: 6,
    minWidth: 120,
    textAlign: 'center',
  },

  arenaGiveMoreTimeButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#6E6E76',
    backgroundColor: '#121317',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 2,
  },
  arenaGiveMoreTimeIcon: {
    width: 30,
    height: 30,
  },
  arenaGiveMoreTimePlaceholder: {
    width: 52,
    height: 52,
  },
  arenaFooter: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  arenaTurnButton: {
    minHeight: 56,
    minWidth: 136,
    paddingHorizontal: 18,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderTopLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: '#351013',
    borderWidth: 1,
    borderColor: '#7A1115',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaTurnText: {
    color: '#FF4A4A',
    fontSize: 20,
    fontWeight: '600',
  },
  arenaTurnPlaceholder: {
    minWidth: 124,
    minHeight: 54,
  },
  arenaViolationWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  arenaViolationButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#FF110A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaViolationSymbol: {
    color: '#FFFFFF',
    fontSize: 62,
    fontWeight: '700',
    lineHeight: 62,
    marginTop: -2,
  },
  arenaViolationCount: {
    color: '#F5F5F7',
    fontSize: 44,
    lineHeight: 46,
    fontWeight: '300',
    minWidth: 26,
  },
});

export default styles;
