export type CountryItem = {
  code: string;
  name: string;
  flag: string;
  normalizedName: string;
};

const normalize = (value: string) =>
  String(value || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

const flagFromCode = (code: string) => {
  const upperCode = String(code || '').trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(upperCode)) {
    return '';
  }

  return upperCode
    .split('')
    .map(char => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join('');
};

export const COUNTRIES: CountryItem[] = [
  {code: 'AF', name: 'Afghanistan', normalizedName: normalize('Afghanistan'), flag: flagFromCode('AF')},
  {code: 'AX', name: 'Aland Islands', normalizedName: normalize('Aland Islands'), flag: flagFromCode('AX')},
  {code: 'AL', name: 'Albania', normalizedName: normalize('Albania'), flag: flagFromCode('AL')},
  {code: 'DZ', name: 'Algeria', normalizedName: normalize('Algeria'), flag: flagFromCode('DZ')},
  {code: 'AS', name: 'American Samoa', normalizedName: normalize('American Samoa'), flag: flagFromCode('AS')},
  {code: 'AD', name: 'Andorra', normalizedName: normalize('Andorra'), flag: flagFromCode('AD')},
  {code: 'AO', name: 'Angola', normalizedName: normalize('Angola'), flag: flagFromCode('AO')},
  {code: 'AI', name: 'Anguilla', normalizedName: normalize('Anguilla'), flag: flagFromCode('AI')},
  {code: 'AQ', name: 'Antarctica', normalizedName: normalize('Antarctica'), flag: flagFromCode('AQ')},
  {code: 'AG', name: 'Antigua and Barbuda', normalizedName: normalize('Antigua and Barbuda'), flag: flagFromCode('AG')},
  {code: 'AR', name: 'Argentina', normalizedName: normalize('Argentina'), flag: flagFromCode('AR')},
  {code: 'AM', name: 'Armenia', normalizedName: normalize('Armenia'), flag: flagFromCode('AM')},
  {code: 'AW', name: 'Aruba', normalizedName: normalize('Aruba'), flag: flagFromCode('AW')},
  {code: 'AU', name: 'Australia', normalizedName: normalize('Australia'), flag: flagFromCode('AU')},
  {code: 'AT', name: 'Austria', normalizedName: normalize('Austria'), flag: flagFromCode('AT')},
  {code: 'AZ', name: 'Azerbaijan', normalizedName: normalize('Azerbaijan'), flag: flagFromCode('AZ')},
  {code: 'BS', name: 'Bahamas', normalizedName: normalize('Bahamas'), flag: flagFromCode('BS')},
  {code: 'BH', name: 'Bahrain', normalizedName: normalize('Bahrain'), flag: flagFromCode('BH')},
  {code: 'BD', name: 'Bangladesh', normalizedName: normalize('Bangladesh'), flag: flagFromCode('BD')},
  {code: 'BB', name: 'Barbados', normalizedName: normalize('Barbados'), flag: flagFromCode('BB')},
  {code: 'BY', name: 'Belarus', normalizedName: normalize('Belarus'), flag: flagFromCode('BY')},
  {code: 'BE', name: 'Belgium', normalizedName: normalize('Belgium'), flag: flagFromCode('BE')},
  {code: 'BZ', name: 'Belize', normalizedName: normalize('Belize'), flag: flagFromCode('BZ')},
  {code: 'BJ', name: 'Benin', normalizedName: normalize('Benin'), flag: flagFromCode('BJ')},
  {code: 'BM', name: 'Bermuda', normalizedName: normalize('Bermuda'), flag: flagFromCode('BM')},
  {code: 'BT', name: 'Bhutan', normalizedName: normalize('Bhutan'), flag: flagFromCode('BT')},
  {code: 'BO', name: 'Bolivia', normalizedName: normalize('Bolivia'), flag: flagFromCode('BO')},
  {code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', normalizedName: normalize('Bonaire, Sint Eustatius and Saba'), flag: flagFromCode('BQ')},
  {code: 'BA', name: 'Bosnia and Herzegovina', normalizedName: normalize('Bosnia and Herzegovina'), flag: flagFromCode('BA')},
  {code: 'BW', name: 'Botswana', normalizedName: normalize('Botswana'), flag: flagFromCode('BW')},
  {code: 'BV', name: 'Bouvet Island', normalizedName: normalize('Bouvet Island'), flag: flagFromCode('BV')},
  {code: 'BR', name: 'Brazil', normalizedName: normalize('Brazil'), flag: flagFromCode('BR')},
  {code: 'IO', name: 'British Indian Ocean Territory', normalizedName: normalize('British Indian Ocean Territory'), flag: flagFromCode('IO')},
  {code: 'VG', name: 'British Virgin Islands', normalizedName: normalize('British Virgin Islands'), flag: flagFromCode('VG')},
  {code: 'BN', name: 'Brunei Darussalam', normalizedName: normalize('Brunei Darussalam'), flag: flagFromCode('BN')},
  {code: 'BG', name: 'Bulgaria', normalizedName: normalize('Bulgaria'), flag: flagFromCode('BG')},
  {code: 'BF', name: 'Burkina Faso', normalizedName: normalize('Burkina Faso'), flag: flagFromCode('BF')},
  {code: 'BI', name: 'Burundi', normalizedName: normalize('Burundi'), flag: flagFromCode('BI')},
  {code: 'CV', name: 'Cabo Verde', normalizedName: normalize('Cabo Verde'), flag: flagFromCode('CV')},
  {code: 'KH', name: 'Cambodia', normalizedName: normalize('Cambodia'), flag: flagFromCode('KH')},
  {code: 'CM', name: 'Cameroon', normalizedName: normalize('Cameroon'), flag: flagFromCode('CM')},
  {code: 'CA', name: 'Canada', normalizedName: normalize('Canada'), flag: flagFromCode('CA')},
  {code: 'KY', name: 'Cayman Islands', normalizedName: normalize('Cayman Islands'), flag: flagFromCode('KY')},
  {code: 'CF', name: 'Central African Republic', normalizedName: normalize('Central African Republic'), flag: flagFromCode('CF')},
  {code: 'TD', name: 'Chad', normalizedName: normalize('Chad'), flag: flagFromCode('TD')},
  {code: 'CL', name: 'Chile', normalizedName: normalize('Chile'), flag: flagFromCode('CL')},
  {code: 'CN', name: 'China', normalizedName: normalize('China'), flag: flagFromCode('CN')},
  {code: 'CX', name: 'Christmas Island', normalizedName: normalize('Christmas Island'), flag: flagFromCode('CX')},
  {code: 'CC', name: 'Cocos (Keeling) Islands', normalizedName: normalize('Cocos (Keeling) Islands'), flag: flagFromCode('CC')},
  {code: 'CO', name: 'Colombia', normalizedName: normalize('Colombia'), flag: flagFromCode('CO')},
  {code: 'KM', name: 'Comoros', normalizedName: normalize('Comoros'), flag: flagFromCode('KM')},
  {code: 'CG', name: 'Congo', normalizedName: normalize('Congo'), flag: flagFromCode('CG')},
  {code: 'CK', name: 'Cook Islands', normalizedName: normalize('Cook Islands'), flag: flagFromCode('CK')},
  {code: 'CR', name: 'Costa Rica', normalizedName: normalize('Costa Rica'), flag: flagFromCode('CR')},
  {code: 'CI', name: 'Cote d\'Ivoire', normalizedName: normalize("Cote d'Ivoire"), flag: flagFromCode('CI')},
  {code: 'HR', name: 'Croatia', normalizedName: normalize('Croatia'), flag: flagFromCode('HR')},
  {code: 'CU', name: 'Cuba', normalizedName: normalize('Cuba'), flag: flagFromCode('CU')},
  {code: 'CW', name: 'Curacao', normalizedName: normalize('Curacao'), flag: flagFromCode('CW')},
  {code: 'CY', name: 'Cyprus', normalizedName: normalize('Cyprus'), flag: flagFromCode('CY')},
  {code: 'CZ', name: 'Czech Republic', normalizedName: normalize('Czech Republic'), flag: flagFromCode('CZ')},
  {code: 'CD', name: 'Democratic Republic of the Congo', normalizedName: normalize('Democratic Republic of the Congo'), flag: flagFromCode('CD')},
  {code: 'DK', name: 'Denmark', normalizedName: normalize('Denmark'), flag: flagFromCode('DK')},
  {code: 'DJ', name: 'Djibouti', normalizedName: normalize('Djibouti'), flag: flagFromCode('DJ')},
  {code: 'DM', name: 'Dominica', normalizedName: normalize('Dominica'), flag: flagFromCode('DM')},
  {code: 'DO', name: 'Dominican Republic', normalizedName: normalize('Dominican Republic'), flag: flagFromCode('DO')},
  {code: 'EC', name: 'Ecuador', normalizedName: normalize('Ecuador'), flag: flagFromCode('EC')},
  {code: 'EG', name: 'Egypt', normalizedName: normalize('Egypt'), flag: flagFromCode('EG')},
  {code: 'SV', name: 'El Salvador', normalizedName: normalize('El Salvador'), flag: flagFromCode('SV')},
  {code: 'GB-ENG', name: 'England', normalizedName: normalize('England'), flag: ''},
  {code: 'GQ', name: 'Equatorial Guinea', normalizedName: normalize('Equatorial Guinea'), flag: flagFromCode('GQ')},
  {code: 'ER', name: 'Eritrea', normalizedName: normalize('Eritrea'), flag: flagFromCode('ER')},
  {code: 'EE', name: 'Estonia', normalizedName: normalize('Estonia'), flag: flagFromCode('EE')},
  {code: 'ET', name: 'Ethiopia', normalizedName: normalize('Ethiopia'), flag: flagFromCode('ET')},
  {code: 'FK', name: 'Falkland Islands', normalizedName: normalize('Falkland Islands'), flag: flagFromCode('FK')},
  {code: 'FO', name: 'Faroe Islands', normalizedName: normalize('Faroe Islands'), flag: flagFromCode('FO')},
  {code: 'FM', name: 'Federated States of Micronesia', normalizedName: normalize('Federated States of Micronesia'), flag: flagFromCode('FM')},
  {code: 'FJ', name: 'Fiji', normalizedName: normalize('Fiji'), flag: flagFromCode('FJ')},
  {code: 'FI', name: 'Finland', normalizedName: normalize('Finland'), flag: flagFromCode('FI')},
  {code: 'FR', name: 'France', normalizedName: normalize('France'), flag: flagFromCode('FR')},
  {code: 'GF', name: 'French Guiana', normalizedName: normalize('French Guiana'), flag: flagFromCode('GF')},
  {code: 'PF', name: 'French Polynesia', normalizedName: normalize('French Polynesia'), flag: flagFromCode('PF')},
  {code: 'TF', name: 'French Southern Territories', normalizedName: normalize('French Southern Territories'), flag: flagFromCode('TF')},
  {code: 'GA', name: 'Gabon', normalizedName: normalize('Gabon'), flag: flagFromCode('GA')},
  {code: 'GM', name: 'Gambia', normalizedName: normalize('Gambia'), flag: flagFromCode('GM')},
  {code: 'GE', name: 'Georgia', normalizedName: normalize('Georgia'), flag: flagFromCode('GE')},
  {code: 'DE', name: 'Germany', normalizedName: normalize('Germany'), flag: flagFromCode('DE')},
  {code: 'GH', name: 'Ghana', normalizedName: normalize('Ghana'), flag: flagFromCode('GH')},
  {code: 'GI', name: 'Gibraltar', normalizedName: normalize('Gibraltar'), flag: flagFromCode('GI')},
  {code: 'GB-SCT', name: 'Great Britain', normalizedName: normalize('Great Britain'), flag: ''},
  {code: 'GR', name: 'Greece', normalizedName: normalize('Greece'), flag: flagFromCode('GR')},
  {code: 'GL', name: 'Greenland', normalizedName: normalize('Greenland'), flag: flagFromCode('GL')},
  {code: 'GD', name: 'Grenada', normalizedName: normalize('Grenada'), flag: flagFromCode('GD')},
  {code: 'GP', name: 'Guadeloupe', normalizedName: normalize('Guadeloupe'), flag: flagFromCode('GP')},
  {code: 'GU', name: 'Guam', normalizedName: normalize('Guam'), flag: flagFromCode('GU')},
  {code: 'GT', name: 'Guatemala', normalizedName: normalize('Guatemala'), flag: flagFromCode('GT')},
  {code: 'GG', name: 'Guernsey', normalizedName: normalize('Guernsey'), flag: flagFromCode('GG')},
  {code: 'GN', name: 'Guinea', normalizedName: normalize('Guinea'), flag: flagFromCode('GN')},
  {code: 'GW', name: 'Guinea-Bissau', normalizedName: normalize('Guinea-Bissau'), flag: flagFromCode('GW')},
  {code: 'GY', name: 'Guyana', normalizedName: normalize('Guyana'), flag: flagFromCode('GY')},
  {code: 'HT', name: 'Haiti', normalizedName: normalize('Haiti'), flag: flagFromCode('HT')},
  {code: 'HM', name: 'Heard Island and McDonald Islands', normalizedName: normalize('Heard Island and McDonald Islands'), flag: flagFromCode('HM')},
  {code: 'HN', name: 'Honduras', normalizedName: normalize('Honduras'), flag: flagFromCode('HN')},
  {code: 'HK', name: 'Hong Kong', normalizedName: normalize('Hong Kong'), flag: flagFromCode('HK')},
  {code: 'HU', name: 'Hungary', normalizedName: normalize('Hungary'), flag: flagFromCode('HU')},
  {code: 'IS', name: 'Iceland', normalizedName: normalize('Iceland'), flag: flagFromCode('IS')},
  {code: 'IN', name: 'India', normalizedName: normalize('India'), flag: flagFromCode('IN')},
  {code: 'ID', name: 'Indonesia', normalizedName: normalize('Indonesia'), flag: flagFromCode('ID')},
  {code: 'IR', name: 'Iran', normalizedName: normalize('Iran'), flag: flagFromCode('IR')},
  {code: 'IQ', name: 'Iraq', normalizedName: normalize('Iraq'), flag: flagFromCode('IQ')},
  {code: 'IE', name: 'Ireland', normalizedName: normalize('Ireland'), flag: flagFromCode('IE')},
  {code: 'IM', name: 'Isle of Man', normalizedName: normalize('Isle of Man'), flag: flagFromCode('IM')},
  {code: 'IL', name: 'Israel', normalizedName: normalize('Israel'), flag: flagFromCode('IL')},
  {code: 'IT', name: 'Italy', normalizedName: normalize('Italy'), flag: flagFromCode('IT')},
  {code: 'JM', name: 'Jamaica', normalizedName: normalize('Jamaica'), flag: flagFromCode('JM')},
  {code: 'JP', name: 'Japan', normalizedName: normalize('Japan'), flag: flagFromCode('JP')},
  {code: 'JE', name: 'Jersey', normalizedName: normalize('Jersey'), flag: flagFromCode('JE')},
  {code: 'JO', name: 'Jordan', normalizedName: normalize('Jordan'), flag: flagFromCode('JO')},
  {code: 'KZ', name: 'Kazakhstan', normalizedName: normalize('Kazakhstan'), flag: flagFromCode('KZ')},
  {code: 'KE', name: 'Kenya', normalizedName: normalize('Kenya'), flag: flagFromCode('KE')},
  {code: 'KI', name: 'Kiribati', normalizedName: normalize('Kiribati'), flag: flagFromCode('KI')},
  {code: 'KW', name: 'Kuwait', normalizedName: normalize('Kuwait'), flag: flagFromCode('KW')},
  {code: 'KG', name: 'Kyrgyzstan', normalizedName: normalize('Kyrgyzstan'), flag: flagFromCode('KG')},
  {code: 'LA', name: 'Laos', normalizedName: normalize('Laos'), flag: flagFromCode('LA')},
  {code: 'LV', name: 'Latvia', normalizedName: normalize('Latvia'), flag: flagFromCode('LV')},
  {code: 'LB', name: 'Lebanon', normalizedName: normalize('Lebanon'), flag: flagFromCode('LB')},
  {code: 'LS', name: 'Lesotho', normalizedName: normalize('Lesotho'), flag: flagFromCode('LS')},
  {code: 'LR', name: 'Liberia', normalizedName: normalize('Liberia'), flag: flagFromCode('LR')},
  {code: 'LY', name: 'Libya', normalizedName: normalize('Libya'), flag: flagFromCode('LY')},
  {code: 'LI', name: 'Liechtenstein', normalizedName: normalize('Liechtenstein'), flag: flagFromCode('LI')},
  {code: 'LT', name: 'Lithuania', normalizedName: normalize('Lithuania'), flag: flagFromCode('LT')},
  {code: 'LU', name: 'Luxembourg', normalizedName: normalize('Luxembourg'), flag: flagFromCode('LU')},
  {code: 'MO', name: 'Macau', normalizedName: normalize('Macau'), flag: flagFromCode('MO')},
  {code: 'MK', name: 'Macedonia', normalizedName: normalize('Macedonia'), flag: flagFromCode('MK')},
  {code: 'MG', name: 'Madagascar', normalizedName: normalize('Madagascar'), flag: flagFromCode('MG')},
  {code: 'MW', name: 'Malawi', normalizedName: normalize('Malawi'), flag: flagFromCode('MW')},
  {code: 'MY', name: 'Malaysia', normalizedName: normalize('Malaysia'), flag: flagFromCode('MY')},
  {code: 'MV', name: 'Maldives', normalizedName: normalize('Maldives'), flag: flagFromCode('MV')},
  {code: 'ML', name: 'Mali', normalizedName: normalize('Mali'), flag: flagFromCode('ML')},
  {code: 'MT', name: 'Malta', normalizedName: normalize('Malta'), flag: flagFromCode('MT')},
  {code: 'MH', name: 'Marshall Islands', normalizedName: normalize('Marshall Islands'), flag: flagFromCode('MH')},
  {code: 'MQ', name: 'Martinique', normalizedName: normalize('Martinique'), flag: flagFromCode('MQ')},
  {code: 'MR', name: 'Mauritania', normalizedName: normalize('Mauritania'), flag: flagFromCode('MR')},
  {code: 'MU', name: 'Mauritius', normalizedName: normalize('Mauritius'), flag: flagFromCode('MU')},
  {code: 'YT', name: 'Mayotte', normalizedName: normalize('Mayotte'), flag: flagFromCode('YT')},
  {code: 'MX', name: 'Mexico', normalizedName: normalize('Mexico'), flag: flagFromCode('MX')},
  {code: 'MD', name: 'Moldova', normalizedName: normalize('Moldova'), flag: flagFromCode('MD')},
  {code: 'MC', name: 'Monaco', normalizedName: normalize('Monaco'), flag: flagFromCode('MC')},
  {code: 'MN', name: 'Mongolia', normalizedName: normalize('Mongolia'), flag: flagFromCode('MN')},
  {code: 'ME', name: 'Montenegro', normalizedName: normalize('Montenegro'), flag: flagFromCode('ME')},
  {code: 'MS', name: 'Montserrat', normalizedName: normalize('Montserrat'), flag: flagFromCode('MS')},
  {code: 'MA', name: 'Morocco', normalizedName: normalize('Morocco'), flag: flagFromCode('MA')},
  {code: 'MZ', name: 'Mozambique', normalizedName: normalize('Mozambique'), flag: flagFromCode('MZ')},
  {code: 'MM', name: 'Myanmar', normalizedName: normalize('Myanmar'), flag: flagFromCode('MM')},
  {code: 'NA', name: 'Namibia', normalizedName: normalize('Namibia'), flag: flagFromCode('NA')},
  {code: 'NR', name: 'Nauru', normalizedName: normalize('Nauru'), flag: flagFromCode('NR')},
  {code: 'NP', name: 'Nepal', normalizedName: normalize('Nepal'), flag: flagFromCode('NP')},
  {code: 'NL', name: 'Netherlands', normalizedName: normalize('Netherlands'), flag: flagFromCode('NL')},
  {code: 'AN', name: 'Netherlands Antilles', normalizedName: normalize('Netherlands Antilles'), flag: flagFromCode('AN')},
  {code: 'NC', name: 'New Caledonia', normalizedName: normalize('New Caledonia'), flag: flagFromCode('NC')},
  {code: 'NZ', name: 'New Zealand', normalizedName: normalize('New Zealand'), flag: flagFromCode('NZ')},
  {code: 'NI', name: 'Nicaragua', normalizedName: normalize('Nicaragua'), flag: flagFromCode('NI')},
  {code: 'NE', name: 'Niger', normalizedName: normalize('Niger'), flag: flagFromCode('NE')},
  {code: 'NG', name: 'Nigeria', normalizedName: normalize('Nigeria'), flag: flagFromCode('NG')},
  {code: 'NU', name: 'Niue', normalizedName: normalize('Niue'), flag: flagFromCode('NU')},
  {code: 'NF', name: 'Norfolk Island', normalizedName: normalize('Norfolk Island'), flag: flagFromCode('NF')},
  {code: 'KP', name: 'North Korea', normalizedName: normalize('North Korea'), flag: flagFromCode('KP')},
  {code: 'GB-NIR', name: 'Northern Ireland', normalizedName: normalize('Northern Ireland'), flag: ''},
  {code: 'MP', name: 'Northern Mariana Islands', normalizedName: normalize('Northern Mariana Islands'), flag: flagFromCode('MP')},
  {code: 'NO', name: 'Norway', normalizedName: normalize('Norway'), flag: flagFromCode('NO')},
  {code: 'OM', name: 'Oman', normalizedName: normalize('Oman'), flag: flagFromCode('OM')},
  {code: 'PK', name: 'Pakistan', normalizedName: normalize('Pakistan'), flag: flagFromCode('PK')},
  {code: 'PW', name: 'Palau', normalizedName: normalize('Palau'), flag: flagFromCode('PW')},
  {code: 'PS', name: 'Palestine', normalizedName: normalize('Palestine'), flag: flagFromCode('PS')},
  {code: 'PA', name: 'Panama', normalizedName: normalize('Panama'), flag: flagFromCode('PA')},
  {code: 'PG', name: 'Papua New Guinea', normalizedName: normalize('Papua New Guinea'), flag: flagFromCode('PG')},
  {code: 'PY', name: 'Paraguay', normalizedName: normalize('Paraguay'), flag: flagFromCode('PY')},
  {code: 'PE', name: 'Peru', normalizedName: normalize('Peru'), flag: flagFromCode('PE')},
  {code: 'PH', name: 'Philippines', normalizedName: normalize('Philippines'), flag: flagFromCode('PH')},
  {code: 'PN', name: 'Pitcairn', normalizedName: normalize('Pitcairn'), flag: flagFromCode('PN')},
  {code: 'PL', name: 'Poland', normalizedName: normalize('Poland'), flag: flagFromCode('PL')},
  {code: 'PT', name: 'Portugal', normalizedName: normalize('Portugal'), flag: flagFromCode('PT')},
  {code: 'PR', name: 'Puerto Rico', normalizedName: normalize('Puerto Rico'), flag: flagFromCode('PR')},
  {code: 'QA', name: 'Qatar', normalizedName: normalize('Qatar'), flag: flagFromCode('QA')},
  {code: 'KR', name: 'Republic of Korea', normalizedName: normalize('Republic of Korea'), flag: flagFromCode('KR')},
  {code: 'RE', name: 'Reunion', normalizedName: normalize('Reunion'), flag: flagFromCode('RE')},
  {code: 'RO', name: 'Romania', normalizedName: normalize('Romania'), flag: flagFromCode('RO')},
  {code: 'RU', name: 'Russia', normalizedName: normalize('Russia'), flag: flagFromCode('RU')},
  {code: 'RW', name: 'Rwanda', normalizedName: normalize('Rwanda'), flag: flagFromCode('RW')},
  {code: 'BL', name: 'Saint Barthelemy', normalizedName: normalize('Saint Barthelemy'), flag: flagFromCode('BL')},
  {code: 'SH', name: 'Saint Helena', normalizedName: normalize('Saint Helena'), flag: flagFromCode('SH')},
  {code: 'KN', name: 'Saint Kitts and Nevis', normalizedName: normalize('Saint Kitts and Nevis'), flag: flagFromCode('KN')},
  {code: 'LC', name: 'Saint Lucia', normalizedName: normalize('Saint Lucia'), flag: flagFromCode('LC')},
  {code: 'MF', name: 'Saint Martin', normalizedName: normalize('Saint Martin'), flag: flagFromCode('MF')},
  {code: 'PM', name: 'Saint Pierre and Miquelon', normalizedName: normalize('Saint Pierre and Miquelon'), flag: flagFromCode('PM')},
  {code: 'VC', name: 'Saint Vincent and the Grenadines', normalizedName: normalize('Saint Vincent and the Grenadines'), flag: flagFromCode('VC')},
  {code: 'WS', name: 'Samoa', normalizedName: normalize('Samoa'), flag: flagFromCode('WS')},
  {code: 'SM', name: 'San Marino', normalizedName: normalize('San Marino'), flag: flagFromCode('SM')},
  {code: 'ST', name: 'Sao Tome and Principe', normalizedName: normalize('Sao Tome and Principe'), flag: flagFromCode('ST')},
  {code: 'SA', name: 'Saudi Arabia', normalizedName: normalize('Saudi Arabia'), flag: flagFromCode('SA')},
  {code: 'SN', name: 'Senegal', normalizedName: normalize('Senegal'), flag: flagFromCode('SN')},
  {code: 'RS', name: 'Serbia', normalizedName: normalize('Serbia'), flag: flagFromCode('RS')},
  {code: 'SC', name: 'Seychelles', normalizedName: normalize('Seychelles'), flag: flagFromCode('SC')},
  {code: 'SL', name: 'Sierra Leone', normalizedName: normalize('Sierra Leone'), flag: flagFromCode('SL')},
  {code: 'SG', name: 'Singapore', normalizedName: normalize('Singapore'), flag: flagFromCode('SG')},
  {code: 'SX', name: 'Sint Maarten', normalizedName: normalize('Sint Maarten'), flag: flagFromCode('SX')},
  {code: 'SK', name: 'Slovakia', normalizedName: normalize('Slovakia'), flag: flagFromCode('SK')},
  {code: 'SI', name: 'Slovenia', normalizedName: normalize('Slovenia'), flag: flagFromCode('SI')},
  {code: 'SB', name: 'Solomon Islands', normalizedName: normalize('Solomon Islands'), flag: flagFromCode('SB')},
  {code: 'SO', name: 'Somalia', normalizedName: normalize('Somalia'), flag: flagFromCode('SO')},
  {code: 'ZA', name: 'South Africa', normalizedName: normalize('South Africa'), flag: flagFromCode('ZA')},
  {code: 'GS', name: 'South Georgia and the South Sandwich Islands', normalizedName: normalize('South Georgia and the South Sandwich Islands'), flag: flagFromCode('GS')},
  {code: 'SS', name: 'South Sudan', normalizedName: normalize('South Sudan'), flag: flagFromCode('SS')},
  {code: 'ES', name: 'Spain', normalizedName: normalize('Spain'), flag: flagFromCode('ES')},
  {code: 'LK', name: 'Sri Lanka', normalizedName: normalize('Sri Lanka'), flag: flagFromCode('LK')},
  {code: 'SD', name: 'Sudan', normalizedName: normalize('Sudan'), flag: flagFromCode('SD')},
  {code: 'SR', name: 'Suriname', normalizedName: normalize('Suriname'), flag: flagFromCode('SR')},
  {code: 'SJ', name: 'Svalbard and Jan Mayen', normalizedName: normalize('Svalbard and Jan Mayen'), flag: flagFromCode('SJ')},
  {code: 'SZ', name: 'Swaziland', normalizedName: normalize('Swaziland'), flag: flagFromCode('SZ')},
  {code: 'SE', name: 'Sweden', normalizedName: normalize('Sweden'), flag: flagFromCode('SE')},
  {code: 'CH', name: 'Switzerland', normalizedName: normalize('Switzerland'), flag: flagFromCode('CH')},
  {code: 'SY', name: 'Syria', normalizedName: normalize('Syria'), flag: flagFromCode('SY')},
  {code: 'TW', name: 'Taiwan', normalizedName: normalize('Taiwan'), flag: flagFromCode('TW')},
  {code: 'TJ', name: 'Tajikistan', normalizedName: normalize('Tajikistan'), flag: flagFromCode('TJ')},
  {code: 'TZ', name: 'Tanzania', normalizedName: normalize('Tanzania'), flag: flagFromCode('TZ')},
  {code: 'TH', name: 'Thailand', normalizedName: normalize('Thailand'), flag: flagFromCode('TH')},
  {code: 'TL', name: 'Timor-Leste', normalizedName: normalize('Timor-Leste'), flag: flagFromCode('TL')},
  {code: 'TG', name: 'Togo', normalizedName: normalize('Togo'), flag: flagFromCode('TG')},
  {code: 'TK', name: 'Tokelau', normalizedName: normalize('Tokelau'), flag: flagFromCode('TK')},
  {code: 'TO', name: 'Tonga', normalizedName: normalize('Tonga'), flag: flagFromCode('TO')},
  {code: 'TT', name: 'Trinidad and Tobago', normalizedName: normalize('Trinidad and Tobago'), flag: flagFromCode('TT')},
  {code: 'TN', name: 'Tunisia', normalizedName: normalize('Tunisia'), flag: flagFromCode('TN')},
  {code: 'TR', name: 'Turkey', normalizedName: normalize('Turkey'), flag: flagFromCode('TR')},
  {code: 'TM', name: 'Turkmenistan', normalizedName: normalize('Turkmenistan'), flag: flagFromCode('TM')},
  {code: 'TC', name: 'Turks and Caicos Islands', normalizedName: normalize('Turks and Caicos Islands'), flag: flagFromCode('TC')},
  {code: 'TV', name: 'Tuvalu', normalizedName: normalize('Tuvalu'), flag: flagFromCode('TV')},
  {code: 'UG', name: 'Uganda', normalizedName: normalize('Uganda'), flag: flagFromCode('UG')},
  {code: 'UA', name: 'Ukraine', normalizedName: normalize('Ukraine'), flag: flagFromCode('UA')},
  {code: 'AE', name: 'United Arab Emirates', normalizedName: normalize('United Arab Emirates'), flag: flagFromCode('AE')},
  {code: 'GB', name: 'United Kingdom', normalizedName: normalize('United Kingdom'), flag: flagFromCode('GB')},
  {code: 'US', name: 'United States', normalizedName: normalize('United States'), flag: flagFromCode('US')},
  {code: 'UM', name: 'United States Minor Outlying Islands', normalizedName: normalize('United States Minor Outlying Islands'), flag: flagFromCode('UM')},
  {code: 'VI', name: 'United States Virgin Islands', normalizedName: normalize('United States Virgin Islands'), flag: flagFromCode('VI')},
  {code: 'UY', name: 'Uruguay', normalizedName: normalize('Uruguay'), flag: flagFromCode('UY')},
  {code: 'UZ', name: 'Uzbekistan', normalizedName: normalize('Uzbekistan'), flag: flagFromCode('UZ')},
  {code: 'VU', name: 'Vanuatu', normalizedName: normalize('Vanuatu'), flag: flagFromCode('VU')},
  {code: 'VA', name: 'Vatican City', normalizedName: normalize('Vatican City'), flag: flagFromCode('VA')},
  {code: 'VE', name: 'Venezuela', normalizedName: normalize('Venezuela'), flag: flagFromCode('VE')},
  {code: 'VN', name: 'Viet Nam', normalizedName: normalize('Viet Nam'), flag: flagFromCode('VN')},
  {code: 'WF', name: 'Wallis and Futuna', normalizedName: normalize('Wallis and Futuna'), flag: flagFromCode('WF')},
  {code: 'EH', name: 'Western Sahara', normalizedName: normalize('Western Sahara'), flag: flagFromCode('EH')},
  {code: 'GB-WLS', name: 'Wales', normalizedName: normalize('Wales'), flag: ''},
  {code: 'YE', name: 'Yemen', normalizedName: normalize('Yemen'), flag: flagFromCode('YE')},
  {code: 'ZM', name: 'Zambia', normalizedName: normalize('Zambia'), flag: flagFromCode('ZM')},
  {code: 'ZW', name: 'Zimbabwe', normalizedName: normalize('Zimbabwe'), flag: flagFromCode('ZW')},
];

export const normalizeCountryName = normalize;


export const getCountryFlagImageUri = (code?: string, width: number = 80) => {
  const normalizedCode = String(code || '').trim().toLowerCase();
  if (!/^[a-z]{2}$/.test(normalizedCode)) {
    return '';
  }

  const safeWidth = Number.isFinite(width) && width > 0 ? Math.round(width) : 80;
  return `https://flagcdn.com/w${safeWidth}/${normalizedCode}.png`;
};
